# Generated by Django 4.1.7 on 2023-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('displayName', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('profileImage', models.URLField()),
            ],
        ),
    ]
