# Generated by Django 4.1.7 on 2023-03-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_author_id_remove_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='service.author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='service.post'),
        ),
    ]
