# Generated by Django 4.1.7 on 2023-03-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_author_uuid_comment_uuid_post_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': 'inbox'},
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='service.author'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.URLField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
