# Generated by Django 4.1.7 on 2023-03-03 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_author_id_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=255)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('author', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='', max_length=255)),
                ('summary', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('object', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Png'), ('image/jpeg;base64', 'Jpeg'), ('application/base64', 'Application')], default='text/plain', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Followers'), ('FRIENDS', 'Friend'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ImagePosts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.post')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.URLField(max_length=255, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='service.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(default='', max_length=255)),
                ('contentType', models.CharField(max_length=20)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.author')),
            ],
        ),
    ]
