# Generated by Django 4.1.7 on 2023-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_likes_content_type_remove_likes_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
