# Generated by Django 4.1.7 on 2023-03-30 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_likes_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='temp_id',
            field=models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
