# Generated by Django 4.1.7 on 2023-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_imageposts_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
