# Generated by Django 4.1.7 on 2023-03-03 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0008_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='service.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='service.post'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='items',
            field=models.ManyToManyField(default=1, related_name='following', to='service.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='service.author'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='service.author'),
        ),
        migrations.AlterField(
            model_name='imageposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_posts', to='service.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='service.author'),
        ),
    ]
