# Generated by Django 4.1.7 on 2023-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_imageposts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageposts',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='imageposts',
            name='id',
            field=models.URLField(default='1', primary_key=True, serialize=False),
        ),
    ]
