# Generated by Django 4.1.7 on 2023-03-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_rename_user_followers_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'followers'},
        ),
        migrations.AlterModelOptions(
            name='imageposts',
            options={'verbose_name_plural': 'image posts'},
        ),
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': "inbox's"},
        ),
        migrations.AlterModelOptions(
            name='liked',
            options={'verbose_name_plural': 'liked'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'likes'},
        ),
    ]
