# Generated by Django 4.1.7 on 2023-03-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_followers_options_alter_imageposts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='service.author', unique=True),
        ),
    ]
