# Generated by Django 4.1.7 on 2023-04-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_likes_content_type_likes_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='object_id',
        ),
    ]
