# Generated by Django 4.1.7 on 2023-04-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0013_remove_likes_content_type_remove_likes_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='likes',
            name='object_id',
            field=models.URLField(null=True),
        ),
    ]
