# Generated by Django 4.1.7 on 2023-03-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service', '0014_alter_followers_items_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'following'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='object',
        ),
        migrations.AddField(
            model_name='likes',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='likes',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='liked',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='service.author'),
        ),
        migrations.RemoveField(
            model_name='liked',
            name='items',
        ),
        migrations.AlterField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='service.author'),
        ),
        migrations.AddField(
            model_name='liked',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='liked', to='service.likes'),
        ),
    ]
