# Generated by Django 4.1.7 on 2023-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_likes_content_type_likes_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='following',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageposts',
            name='id',
            field=models.URLField(default='1', max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liked',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='likes',
            name='object',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='likes',
            name='object_id',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.URLField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='', max_length=400),
        ),
    ]
