# Generated by Django 4.1.7 on 2023-03-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_following_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
