# Generated by Django 4.1.7 on 2023-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_author_github_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.JSONField(null=True),
        ),
    ]
