# Generated by Django 4.1.7 on 2023-03-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_liked_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='service.author', unique=True),
        ),
    ]
