# Generated by Django 4.1.7 on 2023-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='count',
            new_name='numLikes',
        ),
        migrations.AddField(
            model_name='post',
            name='numLikes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
