# Generated by Django 4.1.7 on 2023-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_rename_count_comment_numlikes_post_numlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
