# Generated by Django 4.1.7 on 2023-03-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_imageposts_options_alter_imageposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='service.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
