# Generated by Django 4.1.7 on 2023-03-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_imageposts_post_alter_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.URLField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
